### ISSUE TITLE
Reading through Stata files with do

### ISSUE THREAD

**Issue by Righolt** [VaccineAndDrugEvaluationCentre/code-diary-sas#12]
Stata comments are currently picked up from a main file and `include` scripts, when the scripts are called using `do` or `run` they are not picked up.

**Comment by rbisewski** [comment]
Alright, I think I see a quick fix, just taking a gander at [this](https://github.com/VaccineAndDrugEvaluationCentre/code-diary-sas/blob/master/source/code_diary.sas#L847) line:

```
%let prx_grab_stata_file = 's/(.*include )(.+\.do)(.*)/$2/'; * Grabs the included script name;
```

So this grabs all the lines that contain the `include ` phrase (note the whitespace char), so I think we can just adjust this to something like:

```
%let prx_grab_stata_file = 's/(.*include |\s?do )(.+\.do)(.*)/$2/'; * Grabs the included script name;
```

That will probably work, I'll see if I can find sometime later today to try and test this.

**Comment by Righolt** [comment]
Add `run` to it as well and insert a test case in the demo. (Note the changelog as well.)

**Comment by rbisewski** [comment]
I have since created a [branch](https://github.com/VaccineAndDrugEvaluationCentre/code-diary-sas/tree/better_stata_parsing) that should hopefully resolve this issue. It seems to work again for the example in that repo, so now I think it is time for a test on the RAS.

I plan on having the new code_diary.sas uploaded to the RAS later today to see if this works, unless you would rather test it?

**Comment by rbisewski** [comment]
The recommended changes have since been made, as per discussion I'll hand it off to you for testing at this time.

**Comment by Righolt** [comment]
It seems to work to me, please test in our production environment and make a pull request if that passes.

**Comment by rbisewski** [comment]
Both Gurpret and I were able to generate a few bugs related to output in certain cases. I'll have to look more into it later this week regarding ideas to solve them.

**Comment by Righolt** [comment]
Please regenerate these bugs in the demo/test in this repo first and do development here.

**Comment by rbisewski** [comment]
After co-ordinating with Gurpret, I have since discovered the cause and tested it off-and-on RAS. I will make a pull request in a second and hopefully this can be merged in.

**Comment by Righolt** [comment]
Done #13
