### ISSUE TITLE
Not handling multi-line comments beginning with **

### ISSUE THREAD

**Issue by barretmonchka** [VaccineAndDrugEvaluationCentre/code-diary-sas#3]
SAS supports multi-line comments beginning with ** and ending with a semi-colon. However, this macro only includes comments that begin with ** if they do not spread across multiple lines. If ** comments span multiple lines they are currently ignored by this macro.

**Comment by Righolt** [comment]
Feature not a bug, even within comment blocks you can add a Code Diary comment:

```
/*
Some random text
Some additional random text
**@note Some very important line;
*/
```
The important line is still parsed by Code Diary.

Out of necessity we need to build on SAS' comment structure, so there have to be some practical limits unfortunately.

**Comment by Righolt** [comment]
@barretmonchka Although, as it popped up again, we do want lines to be breakable and want to carry comment to the next ** line.

**Comment by Righolt** [comment]
@barretmonchka See commit, please test.

**Comment by rbisewski** [comment]
@Righolt I have implemented a number of new comment styles, as detailed in the instructions you gave me on Thursday.

The code itself can be located in my repo, as a fork of the main branch:

https://github.com/rbisewski/code-diary-sas

Recommend another team member test these changes, ideally on a tough or tricky piece of code. Later on, if it all checks out, I can make a pull request so this can eventually be merged.

**Comment by Righolt** [comment]
Resolved
