### ISSUE TITLE
Only top-level section headings are being ordered correctly

### ISSUE THREAD

**Issue by barretmonchka** [VaccineAndDrugEvaluationCentre/code-diary-sas#4]
This macro is not ordering sub-section headings, only the top-level headings.

For example, the sub-sections inclusion and exclusion will not necessarily be ordered as stated in the code below.

```
data work.order_list;
    infile datalines;
    input keyword $1-25 order_no $25-26;

    datalines;
definitions              10
cohort                    20
cohort.inclusion     21
cohort.exclusion    22
methods                30
;

run;
```

**Comment by Righolt** [comment]
This issue seems to be working (see commit) for the test, maybe the on-RAS version is an earlier version. Will do some more work and then sent it to the RAS for testing.

**Comment by Righolt** [comment]
@barretmonchka It works as expected in the test file, I will run your code to try to get to the bottom of the remaining problem.
