### ISSUE TITLE
Comments being pulled from library code

### ISSUE THREAD

**Issue by barretmonchka** [VaccineAndDrugEvaluationCentre/code-diary-sas#5]
When comments are being extracted from library code, they are not appearing correctly. The section heading name and order is incorrect.

In addition, it might be desirable to have library code comments separated from the main research project documentation.

**Comment by Righolt** [comment]
An organization might want guidelines for this, based on inclusion calls to scripts itself there might not be an easy way to determine what is library code and what is not.

**Comment by Righolt** [comment]
This can just be done by prefixing library comment tags with `lib.` and then excluding `lib` in `sections_scrubbed` if desired.

@barretmonchka Do you think more would be required?

**Comment by Righolt** [comment]
Ordering solved in #4, separate lib prefix is usage guidelines for organizations.
