### ISSUE TITLE
Handle long metadata lines

### ISSUE THREAD

**Issue by barretmonchka** [VaccineAndDrugEvaluationCentre/code-diary-sas#6]
Code Diary crashes when executing the %write_metadata submacro when it is called with long metadata parameters such as :title.

**Comment by Righolt** [comment]
The problem was commas in the metadata, fixed using `%bquote`, see commit.

**Comment by Righolt** [comment]
Appearantly an issue can be closed from a commit, when the commit is `Fix #N`. Please test on your project before closing.
